### ISSUE TITLE
Problems..

### ISSUE THREAD

**Issue by TheWanderingTraveller** [nimtra/mkHUD#12]
Ok first of of all, lovely hud amazing but theirs a few issues. One I can't acces "See found weapons" and this is annoying when trading cause Inhave to remove the hud entirely to receive my items, next is war paints.... where do I find them? I'm unable to view war paints as in the inspect one. Please tell me how to fix this or if this is the HUDS problem please fix it. Finally are the buttons some of them are off set just wanted to point that out. This HUD is amazing and I want to keep using but it's hard because of these problems, they're small but very annoying to ignore.

**Comment by kmarcie** [comment]
Fixed the war paint inspect panel not working, nearly 6 years later lol. The found weapons glitch is also fixed.
