### ISSUE TITLE
Submit button not working on match feedback query on the ending screen

### ISSUE THREAD

**Issue by FancyBanana** [nimtra/mkHUD#2]
As title says, when at the end of match (final scoreboard) you are prompted to evaluate your match pressing submit does nothing.
Edit:  Pressing 'x' in the corner of the prompt also does nothing, so there may be  a problem with entire window.

**Comment by FancyBanana** [comment]
OK this is a serious issue, just found out that you can softlock gui because of this.
If you open chat before end scroreboard and matchmaking feedback prompt appears, you can't do anything. All inputs are disabled. This is not huge since you can disconnect, but sctill it take away controll for a minute or so.

**Comment by kmarcie** [comment]
This is fixed now
