### ISSUE TITLE
"Loadout" & "Stats" buttons pressing effect are Inconsistent

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [nimtra/mkHUD#3]
https://i.imgur.com/HO8RfrD.gifv
Like you can see on this .gif,  The buttons pressing effect just overlap with the other elements.
*Tested on a 21:9 3440x1440 configuration*

**Comment by kmarcie** [comment]
The Jungle Inferno update ruined the loadout & stats panel and they became unpressable. Ended up just nuking the buttons so this issue is technically fixed.
