### ISSUE TITLE
*Extremely pointless* "weapon" text is overlapping

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [nimtra/mkHUD#4]
https://i.imgur.com/9ZsVHwd.png
The bar of the "P" is exceeding from the box by 2 pixels.
*Come to think of it, It's might be voluntary*
*Tested on a 21:9 3440x1440 configuration*

**Comment by kmarcie** [comment]
Imgur link is dead. Guessing this is about the ItemEffectMeter labels overlapping when using items like the Sandman or the Cleaver. This happens on various resolutions and then doesn't happen on certain. It looks perfect on 1920x1080, but then as soon as you go to 2560x1440, it gets cut off by a pixel. This is just another one of TF2's numerous bugs with handling font rendering - so I can't do much about it.
