### ISSUE TITLE
"Spotlight" & "New" tag is overlapsing on the Store menu.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [nimtra/mkHUD#5]
https://i.imgur.com/Vlx5j5k.gifv
This might be a bit difficult to read the tags like this.
*Tested on a 21:9 3440x1440 configuration*

**Comment by kmarcie** [comment]
I actually don't have any elements edited in the mann co store panel. Since it was reported so long ago and the imgur link is dead I'm not really sure what to go off of here, so I'll close the ticket.
