### ISSUE TITLE
Spy disguise menu not working on 21:9

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [nimtra/mkHUD#8]
https://i.imgur.com/App585G.jpg
For the moment, that's the only things that don't work, due to the resolution itself... I think...
You can still use it if you remember the keys to press obviously, that's just a visual issue.
*Tested on a 21:9 3440x1440 configuration*

**Comment by kmarcie** [comment]
The text that's supposed to display there is just "Press F2 to change team" or something along the lines of it. I intentionally removed the classes from the display panel. IMO not a huge deal so I'll close it, I'd love to troubleshoot it but I also cant because I dont have a monitor that large lol
